### ISSUE TITLE
Any demo page or status if this works?

### ISSUE THREAD

**Issue by caboosesw** [GordonSmith/d3-bullet#1]
I was going to try to port this as well as a way to somewhat learn D3 V4 but I'd rather tack onto your project if you got this working or mostly working.

I could do a demo page and some docs if it helps.

Also, I couldn't find a way to contact you ...

**Comment by GordonSmith** [comment]
@caboosesw sounds good, for the demo I would suggest a gist, you can use unpkg + @hpcc-js/d3-bullet.

While I have a demo and test rig they are not online (but will be once the bigger project hits the 2.0 milestone).

But to give you an idea, this is what it looks like: https://bl.ocks.org/GordonSmith/7d1421e327436c24e215422b4db46d0c
